### ISSUE TITLE
Crash when killing yourself with a Red Matter Trident in channeling mode

### ISSUE THREAD

**Issue by ToMe25** [pupnewfster/ProjectExtended#1]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
When i kill myself with a Red Matter Trident the game crashes.
I haven't tested whether it also crashed when i kill another player, but i don't think it does.

#### Steps to reproduce:
1.get a Red Matter Trident
2.set it in channeling mode
3.throw it at yourself

#### Version (make sure you are on the latest version before reporting):
**Forge:** 28.1.102
**ProjectE:** 1.0.0B
**ProjectExtended:** 1.0.0

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]
https://pastebin.com/dDtqKVWH

**Comment by pupnewfster** [comment]
I will try to fix this later today but it may be at least a few days before a release is actually made, due to the bug being a missing sanity check in some internal ProjectE code I am using in this addon. It doesn't bother verifying that the player is alive/has an inventory and just assumes the player has one.

**Comment by pupnewfster** [comment]
Should be fixed by updating ProjectE to https://www.curseforge.com/minecraft/mc-mods/projecte/files/2855942

**Comment by ToMe25** [comment]
ok thanks :)
