### ISSUE TITLE
Trident will disappear if thrown over longer distances

### ISSUE THREAD

**Issue by Sar4h-3** [pupnewfster/ProjectExtended#2]
I downloaded the latest version for 1.14.4 
If i throw the red matter Trident, the trident hits (according to the sound) and more often than not won't come back. Tried it flying and not flying with the Rending Gale, but it disappears on me more often than not

**Comment by Sar4h-3** [comment]
apparently it is happening, when it hits in the water. Visually it flings back in my direction, and flys away behind me

**Comment by Sar4h-3** [comment]
same thing for dark matter.

**Comment by pupnewfster** [comment]
I believe this is fixed in ProjectExtended [1.1.0](https://www.curseforge.com/minecraft/mc-mods/projectextended/files/2882564) for MC 1.15.2. If you run into it again, feel free to let me know and I will re-open it. (Not releasing a fix for 1.14.4 as I do not have time to maintain multiple versions of MC at once with how much of my free time has been going into working on Mekanism). I am also not positive it is actually fixed, but I updated some code to match a chance vanilla did in 1.15 for the path that the trident returns along and at the very least it seems a lot smoother/less glitchy. So for this reason I believe it is fixed
